/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Abilities {
  'cha' : bigint,
  'con' : bigint,
  'dex' : bigint,
  'int' : bigint,
  'str' : bigint,
  'wis' : bigint,
}
export interface AllianceTreaty {
  'id' : string,
  'status' : string,
  'terms' : string,
  'breakDate' : string,
  'owner' : Principal,
  'notes' : string,
  'armyId' : string,
  'signedDate' : string,
  'partyA' : string,
  'partyB' : string,
}
export interface AlliedArmy {
  'id' : string,
  'allegiance' : string,
  'name' : string,
  'size' : bigint,
  'notes' : string,
  'commander' : string,
}
export interface Ally {
  'id' : bigint,
  'relationship' : string,
  'name' : string,
  'notes' : string,
  'characterId' : CharacterId,
}
export interface AmnesticLogEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'recipient' : string,
  'notes' : string,
  'armyId' : string,
  'amnesticClass' : string,
  'reason' : string,
}
export interface AncientHistoryEntry {
  'id' : string,
  'era' : string,
  'affectedFactions' : string,
  'owner' : Principal,
  'affectedLocations' : string,
  'date' : string,
  'description' : string,
  'eventTitle' : string,
  'notes' : string,
}
export interface AngelClassEntry {
  'id' : string,
  'angelType' : string,
  'owner' : Principal,
  'notes' : string,
  'armyId' : string,
  'soldierName' : string,
}
export interface AnomalyExposureEntry {
  'id' : string,
  'anomalyType' : string,
  'effects' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'personnelName' : string,
}
export interface AppReminder {
  'id' : string,
  'title' : string,
  'reminderNote' : string,
  'isDismissed' : boolean,
  'eventDate' : bigint,
}
export interface Army {
  'id' : string,
  'logistics' : ArmyLogistics,
  'status' : string,
  'moraleData' : ArmyMoraleData,
  'terrainNotes' : string,
  'powerLevel' : bigint,
  'owner' : Principal,
  'officerAbilities' : Array<ArmyAbility>,
  'commanders' : Array<ArmyCommander>,
  'name' : string,
  'race' : string,
  'size' : bigint,
  'banner' : string,
  'specOpsGroups' : Array<SpecOpsGroup>,
  'foundingDate' : string,
  'commanderAbilities' : Array<ArmyAbility>,
  'commandStructure' : ArmyCommandStructure,
  'alliedArmies' : Array<AlliedArmy>,
  'faction' : string,
  'armyNotes' : ArmyNotes,
  'specialties' : Array<string>,
  'characterId' : CharacterId,
  'trainingLevel' : string,
  'warChest' : bigint,
  'branches' : Array<ArmyBranch>,
  'officers' : Array<ArmyOfficer>,
  'ranks' : Array<ArmyRank>,
  'machinery' : Array<ArmyMachinery>,
  'commandingCharacterId' : [] | [string],
  'moraleRating' : bigint,
  'armyAbilities' : Array<ArmyAbility>,
  'intelligence' : ArmyIntelligence,
  'condition' : string,
}
export interface ArmyAbility {
  'id' : string,
  'cost' : string,
  'name' : string,
  'description' : string,
  'effect' : string,
}
export interface ArmyAlignmentEntry {
  'id' : string,
  'owner' : Principal,
  'moralAxis' : string,
  'lastUpdated' : string,
  'ethicalAxis' : string,
  'notes' : string,
  'armyId' : string,
}
export interface ArmyBranch {
  'id' : string,
  'deploymentLocation' : string,
  'veteranFlag' : boolean,
  'name' : string,
  'headcount' : bigint,
  'officerIds' : Array<string>,
  'machineryIds' : Array<string>,
  'specialties' : Array<string>,
  'trainingLevel' : string,
  'loadouts' : Array<ArmyLoadout>,
  'abilities' : Array<ArmyAbility>,
  'interBranchNotes' : string,
  'condition' : string,
}
export interface ArmyCommandStructure {
  'chainOfCommand' : Array<ChainEntry>,
  'ordersLog' : Array<OrderEntry>,
}
export interface ArmyCommander {
  'id' : string,
  'commandSkills' : Array<string>,
  'signatureAbility' : string,
  'background' : string,
  'name' : string,
  'historyNotes' : string,
  'rankId' : string,
  'abilities' : Array<ArmyAbility>,
  'factionId' : [] | [bigint],
}
export interface ArmyDoctrine {
  'id' : string,
  'title' : string,
  'combatDoctrine' : string,
  'owner' : Principal,
  'lastUpdated' : string,
  'notes' : string,
  'armyId' : string,
  'standingOrders' : string,
  'rulesOfEngagement' : string,
}
export interface ArmyInput {
  'logistics' : ArmyLogistics,
  'status' : string,
  'moraleData' : ArmyMoraleData,
  'terrainNotes' : string,
  'powerLevel' : bigint,
  'officerAbilities' : Array<ArmyAbility>,
  'commanders' : Array<ArmyCommander>,
  'name' : string,
  'race' : string,
  'size' : bigint,
  'banner' : string,
  'specOpsGroups' : Array<SpecOpsGroup>,
  'foundingDate' : string,
  'commanderAbilities' : Array<ArmyAbility>,
  'commandStructure' : ArmyCommandStructure,
  'alliedArmies' : Array<AlliedArmy>,
  'faction' : string,
  'armyNotes' : ArmyNotes,
  'specialties' : Array<string>,
  'characterId' : CharacterId,
  'trainingLevel' : string,
  'warChest' : bigint,
  'branches' : Array<ArmyBranch>,
  'officers' : Array<ArmyOfficer>,
  'ranks' : Array<ArmyRank>,
  'machinery' : Array<ArmyMachinery>,
  'commandingCharacterId' : [] | [string],
  'moraleRating' : bigint,
  'armyAbilities' : Array<ArmyAbility>,
  'intelligence' : ArmyIntelligence,
  'condition' : string,
}
export interface ArmyIntelligence {
  'enemyIntelLog' : Array<EnemyIntelEntry>,
  'scoutReports' : Array<ScoutReport>,
}
export interface ArmyLoadout {
  'id' : string,
  'name' : string,
  'armorType' : string,
  'weaponType' : string,
  'notes' : string,
}
export interface ArmyLogistics {
  'goldReserves' : bigint,
  'supplyLines' : Array<SupplyLine>,
  'injuryNotes' : string,
  'food' : bigint,
  'ammunition' : bigint,
  'casualtiesLog' : Array<CasualtyEntry>,
}
export interface ArmyLootEntry {
  'id' : string,
  'distributed' : boolean,
  'value' : bigint,
  'source' : string,
  'owner' : Principal,
  'name' : string,
  'dateAcquired' : string,
  'lootType' : string,
  'notes' : string,
  'quantity' : bigint,
  'armyId' : string,
}
export interface ArmyMachinery {
  'id' : string,
  'name' : string,
  'damageEffect' : string,
  'machineryType' : string,
  'notes' : string,
  'crewSize' : bigint,
  'condition' : string,
}
export interface ArmyMetadata {
  'id' : string,
  'ageDescription' : string,
  'doctrine' : string,
  'reputationScore' : bigint,
  'owner' : Principal,
  'reputationNotes' : string,
  'foundingDate' : string,
  'moraleWarningEnabled' : boolean,
  'armyId' : string,
  'moraleWarningThreshold' : bigint,
}
export interface ArmyMoraleData {
  'loyaltyTracker' : Array<LoyaltyEntry>,
  'moraleEventsLog' : Array<MoraleEvent>,
}
export interface ArmyMoraleHistoryEntry {
  'modifier' : bigint,
  'notes' : string,
  'timestamp' : string,
  'eventType' : string,
}
export interface ArmyNotes {
  'battlePlannerNotes' : Array<BattlePlanEntry>,
  'generalNotes' : string,
  'campaignLog' : Array<CampaignLogEntry>,
}
export interface ArmyOfficer {
  'id' : string,
  'background' : string,
  'promotionLog' : Array<OfficerPromotion>,
  'name' : string,
  'combatAbility' : bigint,
  'race' : string,
  'leadership' : bigint,
  'notes' : string,
  'rankId' : string,
  'loyalty' : bigint,
  'skills' : Array<string>,
  'factionId' : [] | [bigint],
}
export interface ArmyRank {
  'id' : string,
  'name' : string,
  'tier' : bigint,
  'description' : string,
  'troopCount' : bigint,
}
export interface ArmyRelationship {
  'id' : string,
  'relationship' : string,
  'notes' : string,
  'armyName' : string,
}
export interface ArmyRivalEntry {
  'id' : string,
  'rivalryNote' : string,
  'owner' : Principal,
  'rivalArmyId' : string,
  'notes' : string,
  'armyId' : string,
  'rivalArmyName' : string,
  'winsAgainst' : bigint,
  'startDate' : string,
  'lossesAgainst' : bigint,
}
export interface AscensionLogEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'toRank' : string,
  'notes' : string,
  'fromRank' : string,
  'armyId' : string,
  'soldierName' : string,
  'reason' : string,
}
export interface AttunedItem {
  'id' : string,
  'notes' : string,
  'itemName' : string,
}
export interface BattleEngagement {
  'id' : string,
  'date' : string,
  'name' : string,
  'losses' : string,
  'notes' : string,
  'outcome' : string,
}
export interface BattleOutcome {
  'id' : bigint,
  'result' : string,
  'owner' : Principal,
  'casualties' : string,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'opponent' : string,
}
export interface BattlePlanEntry {
  'id' : string,
  'date' : string,
  'objective' : string,
  'notes' : string,
}
export interface BattleSimResult {
  'winnerName' : string,
  'estimatedCasualties' : string,
  'notes' : string,
  'loserName' : string,
  'outcome' : string,
}
export interface BestiaryCreature {
  'id' : bigint,
  'weaknesses' : string,
  'behaviors' : string,
  'owner' : Principal,
  'name' : string,
  'encounterCount' : bigint,
  'creatureType' : string,
  'notes' : string,
  'immunities' : string,
}
export interface BetrayalLogEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'punishment' : string,
  'traitorName' : string,
  'notes' : string,
  'armyId' : string,
  'offense' : string,
}
export interface BlackBudgetEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'allocation' : string,
  'amount' : string,
  'purpose' : string,
}
export interface BloodOathEntry {
  'id' : string,
  'oathText' : string,
  'broken' : boolean,
  'owner' : Principal,
  'date' : string,
  'swornTo' : string,
  'conditions' : string,
  'armyId' : string,
  'soldierId' : string,
  'breakNotes' : string,
  'soldierName' : string,
}
export interface BloodlineEntry {
  'id' : string,
  'era' : string,
  'relation' : string,
  'owner' : Principal,
  'name' : string,
  'notableAncestors' : string,
  'description' : string,
  'notes' : string,
  'characterId' : string,
}
export interface BountyObjective {
  'id' : string,
  'status' : string,
  'completedAt' : string,
  'reward' : string,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'target' : string,
  'notes' : string,
  'armyId' : string,
  'objectiveType' : string,
}
export interface CalendarEvent {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'date' : string,
  'linkedEncounterId' : string,
  'description' : string,
  'linkedSessionId' : string,
  'notes' : string,
  'category' : string,
}
export interface Campaign {
  'id' : string,
  'status' : string,
  'characterIds' : Array<string>,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'armyIds' : Array<string>,
  'notes' : string,
  'startDate' : string,
}
export interface CampaignEnemy {
  'id' : string,
  'status' : string,
  'knownWeaknesses' : string,
  'knownStrengths' : string,
  'owner' : Principal,
  'name' : string,
  'wins' : bigint,
  'campaignId' : string,
  'description' : string,
  'losses' : bigint,
  'notes' : string,
  'faction' : string,
  'enemyType' : string,
  'linkedArmyEnemyIds' : Array<string>,
  'draws' : bigint,
}
export interface CampaignLogEntry {
  'id' : string,
  'date' : string,
  'entry' : string,
}
export interface CapturedEnemy {
  'id' : bigint,
  'status' : string,
  'background' : string,
  'owner' : Principal,
  'name' : string,
  'rank' : string,
  'notes' : string,
  'faction' : string,
  'armyId' : string,
}
export interface CasualtyEntry {
  'id' : string,
  'troopLosses' : bigint,
  'woundedOfficers' : bigint,
  'date' : string,
  'notes' : string,
  'branchName' : string,
}
export interface CelestialBlessingEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'description' : string,
  'blessingType' : string,
  'armyId' : string,
  'soldierName' : string,
}
export interface ChainEntry {
  'id' : string,
  'officerId' : string,
  'role' : string,
  'reportsToId' : string,
}
export interface Character {
  'ac' : bigint,
  'cha' : bigint,
  'con' : bigint,
  'dex' : bigint,
  'int' : bigint,
  'str' : bigint,
  'wis' : bigint,
  'spellSlots' : Array<bigint>,
  'characterClass' : string,
  'background' : string,
  'hpMax' : bigint,
  'owner' : Principal,
  'gold' : bigint,
  'name' : string,
  'race' : string,
  'hpCurrent' : bigint,
  'level' : bigint,
  'speed' : bigint,
  'gender' : string,
  'notes' : string,
  'portraitUrl' : string,
  'skills' : Skills,
  'proficiencyBonus' : bigint,
  'alignment' : string,
  'initiative' : bigint,
}
export interface CharacterAbility {
  'usesRemaining' : bigint,
  'name' : string,
  'uses' : bigint,
  'description' : string,
  'abilityType' : string,
  'rechargeOn' : string,
  'characterId' : CharacterId,
}
export type CharacterAbilityId = bigint;
export interface CharacterAppearance {
  'age' : string,
  'weight' : string,
  'height' : string,
  'eyeColor' : string,
  'distinguishingMarks' : string,
  'hairColor' : string,
}
export interface CharacterCondition {
  'id' : string,
  'duration' : string,
  'autoRemoveOnRest' : boolean,
  'name' : string,
  'description' : string,
}
export interface CharacterCustomStat {
  'id' : bigint,
  'statId' : bigint,
  'value' : string,
  'owner' : Principal,
  'statName' : string,
  'characterId' : CharacterId,
}
export interface CharacterFeat {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'characterId' : CharacterId,
}
export type CharacterId = bigint;
export interface CharacterInjury {
  'id' : string,
  'recoveryNotes' : string,
  'source' : string,
  'owner' : Principal,
  'estimatedRecovery' : string,
  'description' : string,
  'dateReceived' : string,
  'injuryName' : string,
  'injuryType' : string,
  'recoveryStatus' : string,
  'severity' : string,
  'characterId' : CharacterId,
}
export interface CharacterLegacy {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'date' : string,
  'affectedEntities' : string,
  'impactDescription' : string,
  'notes' : string,
  'characterId' : string,
}
export interface CharacterPhysicalAttack {
  'name' : string,
  'attackBonus' : bigint,
  'description' : string,
  'properties' : string,
  'timesUsed' : bigint,
  'damageDice' : string,
  'damageType' : string,
  'characterId' : CharacterId,
  'range' : string,
}
export type CharacterPhysicalAttackId = bigint;
export interface CharacterProficiency {
  'id' : bigint,
  'name' : string,
  'characterId' : CharacterId,
  'profType' : string,
}
export interface CharacterRelationship {
  'id' : bigint,
  'owner' : Principal,
  'relatedCharacterName' : string,
  'notes' : string,
  'characterId' : string,
  'relationshipType' : string,
}
export interface CharacterSkill {
  'id' : bigint,
  'skillName' : string,
  'expertise' : boolean,
  'proficient' : boolean,
  'characterId' : CharacterId,
}
export type ClassId = bigint;
export interface ClearanceLevelEntry {
  'id' : string,
  'owner' : Principal,
  'level' : bigint,
  'notes' : string,
  'armyId' : string,
  'rankCode' : string,
}
export interface Commendation {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'awardedBy' : string,
  'armyId' : string,
  'medalName' : string,
  'soldierId' : string,
  'soldierName' : string,
  'reason' : string,
}
export interface ConcentrationState {
  'concentrationSpellId' : [] | [string],
  'concentrationSpellName' : [] | [string],
}
export interface ContainmentBreachEntry {
  'id' : string,
  'resolved' : boolean,
  'breach' : string,
  'owner' : Principal,
  'casualties' : bigint,
  'date' : string,
  'scpDesignation' : string,
  'notes' : string,
  'armyId' : string,
}
export interface CorruptionLogEntry {
  'id' : string,
  'source' : string,
  'owner' : Principal,
  'date' : string,
  'corruptionPoints' : bigint,
  'notes' : string,
  'armyId' : string,
  'soldierName' : string,
}
export interface CourtMartialEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'punishment' : string,
  'verdict' : string,
  'notes' : string,
  'armyId' : string,
  'charge' : string,
  'soldierId' : string,
  'soldierName' : string,
}
export interface CurrencyState {
  'gold' : bigint,
  'platinum' : bigint,
  'silver' : bigint,
  'characterId' : CharacterId,
  'copper' : bigint,
  'electrum' : bigint,
}
export interface CursedItemEntry {
  'id' : string,
  'acquiredDate' : string,
  'effects' : string,
  'owner' : Principal,
  'cured' : boolean,
  'curse' : string,
  'notes' : string,
  'itemName' : string,
  'characterId' : string,
  'cureCondition' : string,
}
export interface CustomAbility {
  'owner' : Principal,
  'name' : string,
  'uses' : bigint,
  'description' : string,
  'abilityType' : string,
  'rechargeOn' : string,
}
export type CustomAbilityId = bigint;
export interface CustomClass {
  'features' : Array<Trait>,
  'name' : string,
  'hitDie' : bigint,
  'description' : string,
  'proficiencies' : Array<string>,
}
export interface CustomFeat {
  'id' : bigint,
  'prerequisites' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
}
export interface CustomItem {
  'weight' : string,
  'value' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'itemType' : string,
  'rarity' : string,
}
export type CustomItemId = bigint;
export interface CustomPhysicalAttack {
  'owner' : Principal,
  'name' : string,
  'attackBonus' : bigint,
  'description' : string,
  'properties' : string,
  'damageDice' : string,
  'damageType' : string,
  'range' : string,
}
export type CustomPhysicalAttackId = bigint;
export interface CustomRace {
  'abilityBonuses' : Abilities,
  'traits' : Array<Trait>,
  'name' : string,
  'description' : string,
  'speed' : bigint,
}
export interface CustomSkill {
  'id' : bigint,
  'statBased' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
}
export interface CustomSpell {
  'duration' : string,
  'owner' : Principal,
  'school' : string,
  'name' : string,
  'damageEffect' : string,
  'components' : string,
  'description' : string,
  'level' : bigint,
  'range' : string,
  'castingTime' : string,
}
export type CustomSpellId = bigint;
export interface CustomSpellSchool { 'owner' : Principal, 'name' : string }
export type CustomSpellSchoolId = bigint;
export interface CustomStat {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'defaultValue' : string,
}
export interface DarkRitualEntry {
  'id' : string,
  'participants' : string,
  'owner' : Principal,
  'ritualName' : string,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'outcome' : string,
  'purpose' : string,
}
export interface DeathSaveState {
  'failures' : bigint,
  'successes' : bigint,
  'characterId' : CharacterId,
}
export interface DefectionEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'rank' : string,
  'notes' : string,
  'toArmyId' : string,
  'soldierName' : string,
  'fromArmyId' : string,
  'reason' : string,
}
export interface DemonClassEntry {
  'id' : string,
  'owner' : Principal,
  'demonType' : string,
  'notes' : string,
  'armyId' : string,
  'abilities' : string,
  'soldierName' : string,
}
export interface DeploymentMapNote {
  'id' : string,
  'terrain' : string,
  'owner' : Principal,
  'lastUpdated' : string,
  'deploymentStatus' : string,
  'strategicNotes' : string,
  'notes' : string,
  'coordinatesNotes' : string,
  'armyId' : string,
  'supplyLineStatus' : string,
  'branchName' : string,
  'location' : string,
}
export interface DiplomacyEntry {
  'id' : string,
  'status' : string,
  'terms' : string,
  'otherFaction' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'otherArmyName' : string,
  'armyId' : string,
  'keyPersons' : string,
  'relationshipType' : string,
}
export interface DivineMandateEntry {
  'id' : string,
  'status' : string,
  'mandate' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'authority' : string,
  'armyId' : string,
}
export interface DreamVisionEntry {
  'id' : string,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'date' : string,
  'relatedEntities' : string,
  'notes' : string,
  'prophetic' : boolean,
  'characterId' : string,
  'visionType' : string,
}
export interface DungeonRoom {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'description' : string,
}
export interface EncounterEntry {
  'id' : string,
  'linkedNpcIds' : Array<bigint>,
  'xpAwarded' : bigint,
  'owner' : Principal,
  'date' : string,
  'difficulty' : string,
  'name' : string,
  'campaignId' : [] | [string],
  'locationId' : [] | [bigint],
  'notes' : string,
  'outcome' : string,
}
export interface EnemyIntelEntry {
  'id' : string,
  'weaknesses' : string,
  'date' : string,
  'notes' : string,
  'enemyName' : string,
  'knownStrength' : string,
}
export interface EnemyProfile {
  'id' : string,
  'knownWeaknesses' : string,
  'knownStrengths' : string,
  'owner' : Principal,
  'name' : string,
  'wins' : bigint,
  'description' : string,
  'losses' : bigint,
  'notes' : string,
  'faction' : string,
  'enemyType' : string,
  'armyId' : string,
  'draws' : bigint,
}
export interface EquipmentSlot {
  'id' : string,
  'itemId' : [] | [string],
  'slotName' : string,
  'notes' : string,
  'itemName' : string,
}
export interface EspionageEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'operationType' : string,
  'agentName' : string,
  'target' : string,
  'notes' : string,
  'armyId' : string,
  'outcome' : string,
}
export interface EthicsReviewEntry {
  'id' : string,
  'action' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'recommendation' : string,
  'reviewer' : string,
}
export interface Faction {
  'id' : bigint,
  'characterAffiliations' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'goals' : string,
  'notes' : string,
  'relationships' : string,
  'armyAffiliations' : string,
  'alignment' : string,
}
export interface FallenSoldierEntry {
  'id' : string,
  'owner' : Principal,
  'cause' : string,
  'date' : string,
  'name' : string,
  'rank' : string,
  'notes' : string,
  'armyId' : string,
}
export interface GainLossDetails {
  'territory' : string,
  'other' : string,
  'supplies' : bigint,
  'gold' : bigint,
  'troops' : bigint,
  'equipmentNotes' : string,
  'intel' : string,
  'officersCasualties' : string,
  'prisoners' : bigint,
}
export interface GainLossEntry {
  'id' : string,
  'interactionType' : string,
  'moraleApplied' : boolean,
  'moraleImpact' : bigint,
  'owner' : Principal,
  'losses' : GainLossDetails,
  'gains' : GainLossDetails,
  'notes' : string,
  'timestamp' : string,
  'enemyName' : string,
  'linkedFactionId' : [] | [bigint],
  'armyId' : string,
  'outcome' : string,
}
export interface HPState {
  'hpMax' : bigint,
  'hpTemp' : bigint,
  'hpCurrent' : bigint,
  'characterId' : CharacterId,
}
export interface HolyRelicEntry {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'origin' : string,
  'description' : string,
  'notes' : string,
  'armyId' : string,
  'holder' : string,
}
export interface HolyWarEntry {
  'id' : string,
  'status' : string,
  'justification' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'warName' : string,
}
export interface ImportCharacterInput {
  'ac' : bigint,
  'cha' : bigint,
  'con' : bigint,
  'dex' : bigint,
  'int' : bigint,
  'str' : bigint,
  'wis' : bigint,
  'spellSlots' : Array<bigint>,
  'characterClass' : string,
  'background' : string,
  'hpMax' : bigint,
  'gold' : bigint,
  'name' : string,
  'race' : string,
  'hpCurrent' : bigint,
  'level' : bigint,
  'speed' : bigint,
  'gender' : string,
  'notes' : string,
  'portraitUrl' : string,
  'skills' : Skills,
  'proficiencyBonus' : bigint,
  'alignment' : string,
  'initiative' : bigint,
}
export interface InfernalDebtEntry {
  'id' : string,
  'status' : string,
  'terms' : string,
  'owner' : Principal,
  'date' : string,
  'debtor' : string,
  'notes' : string,
  'armyId' : string,
  'creditor' : string,
}
export interface InitiativeEntry {
  'id' : string,
  'maxHp' : bigint,
  'dexModifier' : bigint,
  'currentHp' : bigint,
  'name' : string,
  'initiativeRoll' : bigint,
  'isPlayer' : boolean,
  'conditions' : Array<string>,
}
export interface InitiativeTracker {
  'id' : string,
  'entries' : Array<InitiativeEntry>,
  'currentTurnIndex' : bigint,
  'roundNumber' : bigint,
  'encounterId' : string,
}
export interface InspirationState { 'labelText' : string, 'points' : bigint }
export interface InterPresetWarEntry {
  'id' : string,
  'endDate' : string,
  'owner' : Principal,
  'preset1' : string,
  'preset2' : string,
  'army2Name' : string,
  'notes' : string,
  'conflictName' : string,
  'outcome' : string,
  'army1Name' : string,
  'startDate' : string,
}
export interface InventoryItem {
  'weight' : bigint,
  'name' : string,
  'description' : string,
  'equipped' : boolean,
  'quantity' : bigint,
  'characterId' : CharacterId,
}
export type InventoryItemId = bigint;
export interface Language {
  'id' : bigint,
  'name' : string,
  'characterId' : CharacterId,
}
export interface Location {
  'id' : string,
  'region' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'visitedDate' : string,
  'notes' : string,
  'locationType' : string,
  'factionId' : [] | [bigint],
}
export interface LootDistributionEntry {
  'id' : string,
  'recipient' : string,
  'notes' : string,
  'timestamp' : bigint,
  'itemName' : string,
  'quantity' : bigint,
}
export interface LoreEntry {
  'id' : string,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : string,
  'category' : string,
}
export interface LostKnowledgeEntry {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'notes' : string,
  'category' : string,
  'discoveredBy' : string,
  'discoveredDate' : string,
  'condition' : string,
}
export interface LoyaltyEntry {
  'id' : string,
  'notes' : string,
  'entityName' : string,
  'loyaltyScore' : bigint,
}
export interface MIAEntry {
  'id' : string,
  'status' : string,
  'lastKnownLocation' : string,
  'owner' : Principal,
  'resolvedDate' : string,
  'dateLastSeen' : string,
  'notes' : string,
  'circumstances' : string,
  'armyId' : string,
  'soldierId' : string,
  'soldierName' : string,
}
export interface MoraleEvent {
  'id' : string,
  'impact' : string,
  'date' : string,
  'event' : string,
}
export interface MulticlassEntry {
  'id' : string,
  'spellcastingMod' : string,
  'level' : bigint,
  'isSpellcaster' : boolean,
  'className' : string,
}
export interface MythologicalFigure {
  'id' : string,
  'powers' : string,
  'figureType' : string,
  'domain' : string,
  'owner' : Principal,
  'name' : string,
  'mythology' : string,
  'notes' : string,
  'relationships' : string,
}
export interface NPC {
  'id' : string,
  'relationship' : string,
  'owner' : Principal,
  'name' : string,
  'race' : string,
  'description' : string,
  'locationId' : [] | [bigint],
  'notes' : string,
  'location' : string,
  'factionId' : [] | [bigint],
}
export interface OfficerDuel {
  'id' : string,
  'date' : string,
  'notes' : string,
  'outcome' : string,
  'officer1' : string,
  'officer2' : string,
}
export interface OfficerPromotion {
  'id' : string,
  'date' : string,
  'toRank' : string,
  'notes' : string,
  'fromRank' : string,
}
export interface OfficerSkill {
  'skillName' : string,
  'effect' : string,
  'rating' : bigint,
}
export interface OfficerSkillEntry {
  'officerId' : string,
  'armyId' : bigint,
  'skills' : Array<OfficerSkill>,
}
export interface OrderEntry {
  'id' : string,
  'order' : string,
  'date' : string,
  'target' : string,
}
export interface PactContractEntry {
  'id' : string,
  'status' : string,
  'terms' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'signed' : boolean,
  'armyId' : string,
  'parties' : string,
}
export interface PartyInventoryItem {
  'id' : string,
  'weight' : string,
  'value' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'notes' : string,
  'quantity' : bigint,
}
export interface PartyNote {
  'id' : string,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : string,
}
export interface PartyXpEntry {
  'id' : string,
  'notes' : string,
  'timestamp' : bigint,
  'sessionId' : string,
  'xpEarned' : bigint,
}
export interface PersonalLootEntry {
  'id' : string,
  'value' : bigint,
  'source' : string,
  'owner' : Principal,
  'kept' : boolean,
  'name' : string,
  'dateAcquired' : string,
  'lootType' : string,
  'notes' : string,
  'quantity' : bigint,
  'characterId' : CharacterId,
}
export interface PlaneRealm {
  'traits' : string,
  'name' : string,
  'description' : string,
  'linkedLocations' : string,
  'planeType' : string,
  'notes' : string,
}
export interface PlaneRealmEntry {
  'id' : string,
  'owner' : Principal,
  'planesOrRealms' : Array<PlaneRealm>,
}
export interface PortalEntry {
  'id' : string,
  'portalName' : string,
  'portalType' : string,
  'owner' : Principal,
  'toLocation' : string,
  'campaignId' : [] | [string],
  'fromLocation' : string,
  'notes' : string,
  'condition' : string,
}
export interface PrayerLogEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'answered' : boolean,
  'notes' : string,
  'prayer' : string,
  'armyId' : string,
}
export interface PrisonerExchangeEntry {
  'id' : string,
  'status' : string,
  'ransomAmount' : bigint,
  'exchangeDetails' : string,
  'owner' : Principal,
  'notes' : string,
  'prisonerFaction' : string,
  'prisonerName' : string,
  'prisonerRank' : string,
  'armyId' : string,
  'capturedDate' : string,
  'capturedFrom' : string,
}
export interface ProphecyEntry {
  'id' : string,
  'relatedFactions' : string,
  'source' : string,
  'owner' : Principal,
  'fulfilled' : boolean,
  'date' : string,
  'text' : string,
  'notes' : string,
  'fulfillmentNotes' : string,
  'relatedCharacters' : string,
}
export interface ProtocolLogEntry {
  'id' : string,
  'protocol' : string,
  'status' : string,
  'owner' : Principal,
  'date' : string,
  'invokedBy' : string,
  'notes' : string,
  'armyId' : string,
  'reason' : string,
}
export interface PsychEvalEntry {
  'id' : string,
  'result' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'reviewer' : string,
  'personnelName' : string,
}
export interface Quest {
  'id' : string,
  'status' : string,
  'reward' : string,
  'title' : string,
  'linkedNpcIds' : Array<bigint>,
  'description' : string,
  'notes' : string,
  'objectives' : string,
  'linkedFactionIds' : Array<bigint>,
}
export type RaceId = bigint;
export interface RaceLinkedContent {
  'linkedAttackIds' : Array<CustomPhysicalAttackId>,
  'linkedSpellIds' : Array<CustomSpellId>,
  'linkedAbilityIds' : Array<CustomAbilityId>,
}
export interface RealmTerritoryEntry {
  'id' : string,
  'status' : string,
  'contested' : boolean,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'realm' : string,
}
export interface ReclassificationEntry {
  'id' : string,
  'toClass' : string,
  'subject' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'reason' : string,
  'fromClass' : string,
}
export interface RecruitmentEntry {
  'id' : string,
  'method' : string,
  'date' : string,
  'notes' : string,
  'amount' : bigint,
  'location' : string,
}
export interface RestState {
  'lastLongRestDate' : [] | [string],
  'longRestsUsed' : bigint,
  'shortRestsUsed' : bigint,
}
export interface RivalEntry {
  'id' : string,
  'status' : string,
  'threatLevel' : string,
  'owner' : Principal,
  'name' : string,
  'wins' : bigint,
  'personalHistory' : string,
  'losses' : bigint,
  'notes' : string,
  'faction' : string,
  'linkedFactionId' : [] | [bigint],
  'currentLocation' : string,
  'characterId' : CharacterId,
  'rivalType' : string,
  'backstory' : string,
}
export interface SaveThrowState {
  'conProf' : boolean,
  'intProf' : boolean,
  'chaProf' : boolean,
  'wisProf' : boolean,
  'characterId' : CharacterId,
  'strProf' : boolean,
  'dexProf' : boolean,
}
export interface ScoutReport {
  'id' : string,
  'area' : string,
  'date' : string,
  'findings' : string,
}
export interface ScpObjectEntry {
  'id' : string,
  'status' : string,
  'owner' : Principal,
  'designation' : string,
  'notes' : string,
  'armyId' : string,
  'objectClass' : string,
  'location' : string,
}
export interface SecretMissionLog {
  'id' : string,
  'title' : string,
  'participants' : string,
  'owner' : Principal,
  'date' : string,
  'objective' : string,
  'notes' : string,
  'armyId' : string,
  'outcome' : string,
  'classification' : string,
}
export interface SessionEntry {
  'id' : string,
  'title' : string,
  'linkedQuestIds' : Array<bigint>,
  'linkedNpcIds' : Array<bigint>,
  'linkedEncounterIds' : Array<bigint>,
  'owner' : Principal,
  'date' : string,
  'loot' : string,
  'campaignId' : [] | [string],
  'summary' : string,
  'xpGained' : bigint,
  'notes' : string,
}
export interface Settings { 'maxLevel' : bigint }
export interface SiegeEntry {
  'id' : string,
  'endDate' : string,
  'owner' : Principal,
  'resourcesConsumed' : string,
  'target' : string,
  'notes' : string,
  'armyId' : string,
  'outcome' : string,
  'breaches' : string,
  'startDate' : string,
}
export interface SinCorruptionEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'level' : bigint,
  'exposureType' : string,
  'notes' : string,
  'armyId' : string,
  'soldierName' : string,
}
export interface SiteAssignmentEntry {
  'id' : string,
  'owner' : Principal,
  'site' : string,
  'notes' : string,
  'armyId' : string,
  'assignedDate' : string,
  'personnelName' : string,
}
export interface Skills {
  'perception' : boolean,
  'animalHandling' : boolean,
  'nature' : boolean,
  'investigation' : boolean,
  'deception' : boolean,
  'sleightOfHand' : boolean,
  'acrobatics' : boolean,
  'description' : string,
  'athletics' : boolean,
  'history' : boolean,
  'persuasion' : boolean,
  'medicine' : boolean,
  'stealth' : boolean,
  'survival' : boolean,
  'insight' : boolean,
  'intimidation' : boolean,
  'performance' : boolean,
  'arcana' : boolean,
  'religion' : boolean,
}
export interface SoldierBio {
  'id' : string,
  'bio' : string,
  'branch' : string,
  'owner' : Principal,
  'rank' : string,
  'armyId' : string,
  'backstory' : string,
  'soldierId' : string,
  'notableHistory' : string,
  'soldierName' : string,
}
export interface SoulBountyEntry {
  'id' : string,
  'status' : string,
  'value' : string,
  'owner' : Principal,
  'date' : string,
  'bountyType' : string,
  'notes' : string,
  'targetName' : string,
  'armyId' : string,
}
export interface SpecOpsGroup {
  'id' : string,
  'missionType' : string,
  'name' : string,
  'headcount' : bigint,
  'officerIds' : Array<string>,
  'equipmentNotes' : string,
  'notes' : string,
  'abilities' : Array<ArmyAbility>,
  'condition' : string,
}
export interface Spell {
  'duration' : string,
  'school' : string,
  'name' : string,
  'damageEffect' : string,
  'components' : string,
  'description' : string,
  'level' : bigint,
  'characterId' : CharacterId,
  'range' : string,
  'castingTime' : string,
}
export type SpellId = bigint;
export interface SpellSlotState {
  'total' : bigint,
  'used' : bigint,
  'characterId' : CharacterId,
  'spellLevel' : bigint,
}
export interface SrdSpell {
  'duration' : string,
  'school' : string,
  'name' : string,
  'damageEffect' : string,
  'components' : string,
  'description' : string,
  'level' : bigint,
  'range' : string,
  'castingTime' : string,
}
export interface SummoningLogEntry {
  'id' : string,
  'status' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'armyId' : string,
  'entityName' : string,
  'purpose' : string,
  'binder' : string,
}
export interface SupplyConsumptionEntry {
  'id' : string,
  'date' : string,
  'foodConsumed' : bigint,
  'ammoConsumed' : bigint,
  'notes' : string,
}
export interface SupplyLine {
  'id' : string,
  'vulnerabilities' : string,
  'notes' : string,
  'route' : string,
}
export interface SupplyRoute {
  'id' : string,
  'status' : string,
  'toLocationId' : string,
  'fromLocationId' : string,
  'notes' : string,
}
export interface TabNote {
  'id' : bigint,
  'content' : string,
  'tabName' : string,
  'characterId' : CharacterId,
}
export interface ThemeSettings {
  'themePreset' : string,
  'accentColor' : string,
}
export interface TimelineEvent {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'date' : string,
  'characters' : Array<string>,
  'description' : string,
  'linkedFactionId' : [] | [bigint],
  'category' : string,
  'armies' : Array<string>,
  'linkedLocationId' : [] | [bigint],
}
export interface TrainingCertification {
  'id' : string,
  'expiresDate' : string,
  'certName' : string,
  'completionDate' : string,
  'owner' : Principal,
  'trainer' : string,
  'notes' : string,
  'armyId' : string,
  'soldierId' : string,
  'soldierName' : string,
}
export interface Trait {
  'source' : string,
  'name' : string,
  'description' : string,
  'characterId' : CharacterId,
}
export type TraitId = bigint;
export interface TrophyEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'name' : string,
  'battle' : string,
  'description' : string,
  'takenFrom' : string,
  'notes' : string,
  'armyId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VeteranUnit {
  'id' : string,
  'owner' : Principal,
  'designation' : string,
  'battleCount' : bigint,
  'notes' : string,
  'armyId' : string,
  'branchId' : string,
  'unitName' : string,
  'reason' : string,
}
export interface WarCrimeEntry {
  'id' : string,
  'owner' : Principal,
  'date' : string,
  'event' : string,
  'notes' : string,
  'perpetrators' : string,
  'armyId' : string,
  'consequence' : string,
  'location' : string,
}
export interface WeatherEntry {
  'id' : bigint,
  'endDate' : string,
  'effects' : string,
  'owner' : Principal,
  'season' : string,
  'notes' : string,
  'weatherType' : string,
  'startDate' : string,
}
export interface WhistleblowerEntry {
  'id' : string,
  'source' : string,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'incident' : string,
  'armyId' : string,
  'contained' : boolean,
}
export interface XpState {
  'xp' : bigint,
  'milestoneNotes' : string,
  'characterId' : CharacterId,
  'milestoneMode' : boolean,
  'totalXpEarned' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAllianceTreaty' : ActorMethod<[AllianceTreaty], string>,
  'addAlly' : ActorMethod<[CharacterId, string, string, string], bigint>,
  'addAmnesticLogEntry' : ActorMethod<[AmnesticLogEntry], string>,
  'addAncientHistoryEntry' : ActorMethod<[AncientHistoryEntry], string>,
  'addAngelClassEntry' : ActorMethod<[AngelClassEntry], string>,
  'addAnomalyExposureEntry' : ActorMethod<[AnomalyExposureEntry], string>,
  'addArmy' : ActorMethod<[ArmyInput], string>,
  'addArmyDoctrine' : ActorMethod<[ArmyDoctrine], string>,
  'addArmyLootEntry' : ActorMethod<[string, ArmyLootEntry], string>,
  'addArmyMoraleEvent' : ActorMethod<[string, ArmyMoraleHistoryEntry], boolean>,
  'addArmyRivalEntry' : ActorMethod<[ArmyRivalEntry], string>,
  'addAscensionLogEntry' : ActorMethod<[AscensionLogEntry], string>,
  'addAttunedItem' : ActorMethod<[CharacterId, AttunedItem], undefined>,
  'addBattleEngagement' : ActorMethod<[string, BattleEngagement], undefined>,
  'addBattleOutcome' : ActorMethod<[BattleOutcome], bigint>,
  'addBestiaryCreature' : ActorMethod<[BestiaryCreature], bigint>,
  'addBetrayalLogEntry' : ActorMethod<[BetrayalLogEntry], string>,
  'addBlackBudgetEntry' : ActorMethod<[BlackBudgetEntry], string>,
  'addBloodOathEntry' : ActorMethod<[BloodOathEntry], string>,
  'addBloodlineEntry' : ActorMethod<[BloodlineEntry], string>,
  'addBountyObjective' : ActorMethod<[string, BountyObjective], string>,
  'addCalendarEvent' : ActorMethod<[CalendarEvent], bigint>,
  'addCampaign' : ActorMethod<[Campaign], undefined>,
  'addCampaignEnemy' : ActorMethod<[string, CampaignEnemy], string>,
  'addCapturedEnemy' : ActorMethod<[CapturedEnemy], bigint>,
  'addCelestialBlessing' : ActorMethod<[CelestialBlessingEntry], string>,
  'addCharacterAbility' : ActorMethod<[CharacterAbility], CharacterAbilityId>,
  'addCharacterCustomStat' : ActorMethod<
    [CharacterId, bigint, string, string],
    bigint
  >,
  'addCharacterFeat' : ActorMethod<[CharacterId, string, string], bigint>,
  'addCharacterInjury' : ActorMethod<[CharacterId, CharacterInjury], string>,
  'addCharacterLegacy' : ActorMethod<[CharacterLegacy], string>,
  'addCharacterPhysicalAttack' : ActorMethod<
    [CharacterPhysicalAttack],
    CharacterPhysicalAttackId
  >,
  'addCharacterProficiency' : ActorMethod<
    [CharacterId, string, string],
    bigint
  >,
  'addCharacterRelationship' : ActorMethod<[CharacterRelationship], bigint>,
  'addCharacterSkill' : ActorMethod<
    [CharacterId, string, boolean, boolean],
    bigint
  >,
  'addClass' : ActorMethod<[CustomClass], ClassId>,
  'addClearanceLevelEntry' : ActorMethod<[ClearanceLevelEntry], string>,
  'addCommendation' : ActorMethod<[Commendation], string>,
  'addContainmentBreachEntry' : ActorMethod<[ContainmentBreachEntry], string>,
  'addCorruptionLogEntry' : ActorMethod<[CorruptionLogEntry], string>,
  'addCourtMartialEntry' : ActorMethod<[CourtMartialEntry], string>,
  'addCursedItemEntry' : ActorMethod<[CursedItemEntry], string>,
  'addCustomAbility' : ActorMethod<[CustomAbility], CustomAbilityId>,
  'addCustomFeat' : ActorMethod<[string, string, string], bigint>,
  'addCustomItem' : ActorMethod<[CustomItem], CustomItemId>,
  'addCustomPhysicalAttack' : ActorMethod<
    [CustomPhysicalAttack],
    CustomPhysicalAttackId
  >,
  'addCustomSkill' : ActorMethod<[string, string, string], bigint>,
  'addCustomSpell' : ActorMethod<[CustomSpell], CustomSpellId>,
  'addCustomSpellSchool' : ActorMethod<
    [CustomSpellSchool],
    CustomSpellSchoolId
  >,
  'addCustomStat' : ActorMethod<[string, string, string], bigint>,
  'addDarkRitualEntry' : ActorMethod<[DarkRitualEntry], string>,
  'addDefectionEntry' : ActorMethod<[DefectionEntry], string>,
  'addDemonClassEntry' : ActorMethod<[DemonClassEntry], string>,
  'addDeploymentNote' : ActorMethod<[string, DeploymentMapNote], string>,
  'addDiplomacyEntry' : ActorMethod<[string, DiplomacyEntry], string>,
  'addDivineMandate' : ActorMethod<[DivineMandateEntry], string>,
  'addDreamVisionEntry' : ActorMethod<[DreamVisionEntry], string>,
  'addEncounterEntry' : ActorMethod<[EncounterEntry], undefined>,
  'addEnemyProfile' : ActorMethod<[string, EnemyProfile], string>,
  'addEspionageEntry' : ActorMethod<[EspionageEntry], string>,
  'addEthicsReviewEntry' : ActorMethod<[EthicsReviewEntry], string>,
  'addFaction' : ActorMethod<[Faction], bigint>,
  'addFallenSoldier' : ActorMethod<[FallenSoldierEntry], string>,
  'addGainLossEntry' : ActorMethod<[string, GainLossEntry], string>,
  'addHolyRelic' : ActorMethod<[HolyRelicEntry], string>,
  'addHolyWarEntry' : ActorMethod<[HolyWarEntry], string>,
  'addInfernalDebtEntry' : ActorMethod<[InfernalDebtEntry], string>,
  'addInterPresetWarEntry' : ActorMethod<[InterPresetWarEntry], string>,
  'addItem' : ActorMethod<[InventoryItem], InventoryItemId>,
  'addLanguage' : ActorMethod<[CharacterId, string], bigint>,
  'addLocation' : ActorMethod<[Location], undefined>,
  'addLootDistributionEntry' : ActorMethod<[LootDistributionEntry], boolean>,
  'addLoreEntry' : ActorMethod<[LoreEntry], undefined>,
  'addLostKnowledgeEntry' : ActorMethod<[LostKnowledgeEntry], string>,
  'addMIAEntry' : ActorMethod<[MIAEntry], string>,
  'addMythologicalFigure' : ActorMethod<[MythologicalFigure], string>,
  'addNPC' : ActorMethod<[NPC], undefined>,
  'addOfficerDuel' : ActorMethod<[string, OfficerDuel], undefined>,
  'addPactContractEntry' : ActorMethod<[PactContractEntry], string>,
  'addPartyInventoryItem' : ActorMethod<[PartyInventoryItem], undefined>,
  'addPartyNote' : ActorMethod<[PartyNote], undefined>,
  'addPartyXpEntry' : ActorMethod<[PartyXpEntry], boolean>,
  'addPersonalLootEntry' : ActorMethod<
    [CharacterId, PersonalLootEntry],
    string
  >,
  'addPortalEntry' : ActorMethod<[PortalEntry], string>,
  'addPrayerLogEntry' : ActorMethod<[PrayerLogEntry], string>,
  'addPrisonerExchange' : ActorMethod<[string, PrisonerExchangeEntry], string>,
  'addProphecyEntry' : ActorMethod<[ProphecyEntry], string>,
  'addProtocolLogEntry' : ActorMethod<[ProtocolLogEntry], string>,
  'addPsychEvalEntry' : ActorMethod<[PsychEvalEntry], string>,
  'addQuest' : ActorMethod<[CharacterId, Quest], undefined>,
  'addRace' : ActorMethod<[CustomRace], RaceId>,
  'addRealmTerritoryEntry' : ActorMethod<[RealmTerritoryEntry], string>,
  'addReclassificationEntry' : ActorMethod<[ReclassificationEntry], string>,
  'addRecruitmentEntry' : ActorMethod<[string, RecruitmentEntry], undefined>,
  'addRivalEntry' : ActorMethod<[CharacterId, RivalEntry], string>,
  'addScpObjectEntry' : ActorMethod<[ScpObjectEntry], string>,
  'addSecretMissionLog' : ActorMethod<[SecretMissionLog], string>,
  'addSessionEntry' : ActorMethod<[SessionEntry], undefined>,
  'addSiegeEntry' : ActorMethod<[SiegeEntry], string>,
  'addSinCorruptionEntry' : ActorMethod<[SinCorruptionEntry], string>,
  'addSiteAssignmentEntry' : ActorMethod<[SiteAssignmentEntry], string>,
  'addSoldierBio' : ActorMethod<[SoldierBio], string>,
  'addSoulBountyEntry' : ActorMethod<[SoulBountyEntry], string>,
  'addSpell' : ActorMethod<[Spell], SpellId>,
  'addSummoningLogEntry' : ActorMethod<[SummoningLogEntry], string>,
  'addTimelineEvent' : ActorMethod<[TimelineEvent], undefined>,
  'addTrainingCertification' : ActorMethod<[TrainingCertification], string>,
  'addTrait' : ActorMethod<[Trait], TraitId>,
  'addTrophyEntry' : ActorMethod<[TrophyEntry], string>,
  'addVeteranUnit' : ActorMethod<[VeteranUnit], string>,
  'addWarCrimeEntry' : ActorMethod<[WarCrimeEntry], string>,
  'addWeatherEntry' : ActorMethod<[WeatherEntry], bigint>,
  'addWhistleblowerEntry' : ActorMethod<[WhistleblowerEntry], string>,
  'applyCharacterLevelFromXp' : ActorMethod<[CharacterId], undefined>,
  'applyRaceGrantsToCharacter' : ActorMethod<[CharacterId, RaceId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<[Character], CharacterId>,
  'deleteAllianceTreaty' : ActorMethod<[string], boolean>,
  'deleteAlly' : ActorMethod<[bigint], undefined>,
  'deleteAmnesticLogEntry' : ActorMethod<[string], boolean>,
  'deleteAncientHistoryEntry' : ActorMethod<[string], boolean>,
  'deleteAngelClassEntry' : ActorMethod<[string], boolean>,
  'deleteAnomalyExposureEntry' : ActorMethod<[string], boolean>,
  'deleteAppReminder' : ActorMethod<[string], boolean>,
  'deleteArmy' : ActorMethod<[string], undefined>,
  'deleteArmyDoctrine' : ActorMethod<[string], boolean>,
  'deleteArmyLootEntry' : ActorMethod<[string], boolean>,
  'deleteArmyRivalEntry' : ActorMethod<[string], boolean>,
  'deleteAscensionLogEntry' : ActorMethod<[string], boolean>,
  'deleteBattleEngagement' : ActorMethod<[string, string], undefined>,
  'deleteBattleOutcome' : ActorMethod<[bigint], boolean>,
  'deleteBestiaryCreature' : ActorMethod<[bigint], boolean>,
  'deleteBetrayalLogEntry' : ActorMethod<[string], boolean>,
  'deleteBlackBudgetEntry' : ActorMethod<[string], boolean>,
  'deleteBloodOathEntry' : ActorMethod<[string], boolean>,
  'deleteBloodlineEntry' : ActorMethod<[string], boolean>,
  'deleteBountyObjective' : ActorMethod<[string], boolean>,
  'deleteCalendarEvent' : ActorMethod<[bigint], boolean>,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'deleteCampaignEnemy' : ActorMethod<[string], boolean>,
  'deleteCapturedEnemy' : ActorMethod<[bigint], boolean>,
  'deleteCelestialBlessing' : ActorMethod<[string], boolean>,
  'deleteCharacter' : ActorMethod<[CharacterId], undefined>,
  'deleteCharacterAbility' : ActorMethod<[CharacterAbilityId], undefined>,
  'deleteCharacterCustomStat' : ActorMethod<[bigint], undefined>,
  'deleteCharacterFeat' : ActorMethod<[bigint], undefined>,
  'deleteCharacterInjury' : ActorMethod<[string], boolean>,
  'deleteCharacterLegacy' : ActorMethod<[string], boolean>,
  'deleteCharacterPhysicalAttack' : ActorMethod<
    [CharacterPhysicalAttackId],
    undefined
  >,
  'deleteCharacterProficiency' : ActorMethod<[bigint], undefined>,
  'deleteCharacterRelationship' : ActorMethod<[bigint], boolean>,
  'deleteCharacterSkill' : ActorMethod<[bigint], undefined>,
  'deleteClass' : ActorMethod<[ClassId], undefined>,
  'deleteClearanceLevelEntry' : ActorMethod<[string], boolean>,
  'deleteCommendation' : ActorMethod<[string], boolean>,
  'deleteContainmentBreachEntry' : ActorMethod<[string], boolean>,
  'deleteCorruptionLogEntry' : ActorMethod<[string], boolean>,
  'deleteCourtMartialEntry' : ActorMethod<[string], boolean>,
  'deleteCursedItemEntry' : ActorMethod<[string], boolean>,
  'deleteCustomAbility' : ActorMethod<[CustomAbilityId], undefined>,
  'deleteCustomFeat' : ActorMethod<[bigint], undefined>,
  'deleteCustomItem' : ActorMethod<[CustomItemId], undefined>,
  'deleteCustomPhysicalAttack' : ActorMethod<
    [CustomPhysicalAttackId],
    undefined
  >,
  'deleteCustomSkill' : ActorMethod<[bigint], undefined>,
  'deleteCustomSpell' : ActorMethod<[CustomSpellId], undefined>,
  'deleteCustomSpellSchool' : ActorMethod<[CustomSpellSchoolId], undefined>,
  'deleteCustomStat' : ActorMethod<[bigint], undefined>,
  'deleteDarkRitualEntry' : ActorMethod<[string], boolean>,
  'deleteDefectionEntry' : ActorMethod<[string], boolean>,
  'deleteDemonClassEntry' : ActorMethod<[string], boolean>,
  'deleteDeploymentNote' : ActorMethod<[string], boolean>,
  'deleteDiplomacyEntry' : ActorMethod<[string], boolean>,
  'deleteDivineMandate' : ActorMethod<[string], boolean>,
  'deleteDreamVisionEntry' : ActorMethod<[string], boolean>,
  'deleteEncounterEntry' : ActorMethod<[string], undefined>,
  'deleteEnemyProfile' : ActorMethod<[string], boolean>,
  'deleteEspionageEntry' : ActorMethod<[string], boolean>,
  'deleteEthicsReviewEntry' : ActorMethod<[string], boolean>,
  'deleteFaction' : ActorMethod<[bigint], boolean>,
  'deleteFallenSoldier' : ActorMethod<[string], boolean>,
  'deleteGainLossEntry' : ActorMethod<[string], boolean>,
  'deleteHolyRelic' : ActorMethod<[string], boolean>,
  'deleteHolyWarEntry' : ActorMethod<[string], boolean>,
  'deleteInfernalDebtEntry' : ActorMethod<[string], boolean>,
  'deleteInitiativeTracker' : ActorMethod<[string], boolean>,
  'deleteInterPresetWarEntry' : ActorMethod<[string], boolean>,
  'deleteItem' : ActorMethod<[InventoryItemId], undefined>,
  'deleteLanguage' : ActorMethod<[bigint], undefined>,
  'deleteLocation' : ActorMethod<[string], undefined>,
  'deleteLootDistributionEntry' : ActorMethod<[string], boolean>,
  'deleteLoreEntry' : ActorMethod<[string], undefined>,
  'deleteLostKnowledgeEntry' : ActorMethod<[string], boolean>,
  'deleteMIAEntry' : ActorMethod<[string], boolean>,
  'deleteMythologicalFigure' : ActorMethod<[string], boolean>,
  'deleteNPC' : ActorMethod<[string], undefined>,
  'deleteOfficerDuel' : ActorMethod<[string, string], undefined>,
  'deletePactContractEntry' : ActorMethod<[string], boolean>,
  'deletePartyInventoryItem' : ActorMethod<[string], undefined>,
  'deletePartyNote' : ActorMethod<[string], undefined>,
  'deletePartyXpEntry' : ActorMethod<[string], boolean>,
  'deletePersonalLootEntry' : ActorMethod<[string], boolean>,
  'deletePortalEntry' : ActorMethod<[string], boolean>,
  'deletePrayerLogEntry' : ActorMethod<[string], boolean>,
  'deletePrisonerExchange' : ActorMethod<[string], boolean>,
  'deleteProphecyEntry' : ActorMethod<[string], boolean>,
  'deleteProtocolLogEntry' : ActorMethod<[string], boolean>,
  'deletePsychEvalEntry' : ActorMethod<[string], boolean>,
  'deleteQuest' : ActorMethod<[CharacterId, string], undefined>,
  'deleteRace' : ActorMethod<[RaceId], undefined>,
  'deleteRealmTerritoryEntry' : ActorMethod<[string], boolean>,
  'deleteReclassificationEntry' : ActorMethod<[string], boolean>,
  'deleteRecruitmentEntry' : ActorMethod<[string, string], undefined>,
  'deleteRivalEntry' : ActorMethod<[string], boolean>,
  'deleteScpObjectEntry' : ActorMethod<[string], boolean>,
  'deleteSecretMissionLog' : ActorMethod<[string], boolean>,
  'deleteSessionEntry' : ActorMethod<[string], undefined>,
  'deleteSiegeEntry' : ActorMethod<[string], boolean>,
  'deleteSinCorruptionEntry' : ActorMethod<[string], boolean>,
  'deleteSiteAssignmentEntry' : ActorMethod<[string], boolean>,
  'deleteSoldierBio' : ActorMethod<[string], boolean>,
  'deleteSoulBountyEntry' : ActorMethod<[string], boolean>,
  'deleteSpell' : ActorMethod<[SpellId], undefined>,
  'deleteSummoningLogEntry' : ActorMethod<[string], boolean>,
  'deleteTabNote' : ActorMethod<[CharacterId, string], undefined>,
  'deleteTimelineEvent' : ActorMethod<[string], undefined>,
  'deleteTrainingCertification' : ActorMethod<[string], boolean>,
  'deleteTrait' : ActorMethod<[TraitId], undefined>,
  'deleteTrophyEntry' : ActorMethod<[string], boolean>,
  'deleteVeteranUnit' : ActorMethod<[string], boolean>,
  'deleteWarCrimeEntry' : ActorMethod<[string], boolean>,
  'deleteWeatherEntry' : ActorMethod<[bigint], boolean>,
  'deleteWhistleblowerEntry' : ActorMethod<[string], boolean>,
  'exportAllData' : ActorMethod<[], string>,
  'exportCharacter' : ActorMethod<[CharacterId], string>,
  'getAbilitiesByCharacter' : ActorMethod<
    [CharacterId],
    Array<[CharacterAbilityId, CharacterAbility]>
  >,
  'getAllCharacters' : ActorMethod<[], Array<[CharacterId, Character]>>,
  'getAllCharactersCount' : ActorMethod<[{}], bigint>,
  'getAllClasses' : ActorMethod<[], Array<[ClassId, CustomClass]>>,
  'getAllCustomAbilities' : ActorMethod<
    [],
    Array<[CustomAbilityId, CustomAbility]>
  >,
  'getAllCustomFeats' : ActorMethod<[], Array<CustomFeat>>,
  'getAllCustomItems' : ActorMethod<[], Array<[CustomItemId, CustomItem]>>,
  'getAllCustomPhysicalAttacks' : ActorMethod<
    [],
    Array<[CustomPhysicalAttackId, CustomPhysicalAttack]>
  >,
  'getAllCustomSkills' : ActorMethod<[], Array<CustomSkill>>,
  'getAllCustomSpellSchools' : ActorMethod<
    [],
    Array<[CustomSpellSchoolId, CustomSpellSchool]>
  >,
  'getAllCustomSpells' : ActorMethod<[], Array<[CustomSpellId, CustomSpell]>>,
  'getAllCustomStats' : ActorMethod<[], Array<CustomStat>>,
  'getAllRaceLinkedContent' : ActorMethod<
    [],
    Array<[RaceId, RaceLinkedContent]>
  >,
  'getAllRaces' : ActorMethod<[], Array<[RaceId, CustomRace]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllianceTreaties' : ActorMethod<[string], Array<AllianceTreaty>>,
  'getAlliesByCharacter' : ActorMethod<[CharacterId], Array<Ally>>,
  'getAmnesticLog' : ActorMethod<[string], Array<AmnesticLogEntry>>,
  'getAncientHistoryEntries' : ActorMethod<[], Array<AncientHistoryEntry>>,
  'getAngelClassLog' : ActorMethod<[string], Array<AngelClassEntry>>,
  'getAnomalyExposureLog' : ActorMethod<[string], Array<AnomalyExposureEntry>>,
  'getAppReminders' : ActorMethod<[], Array<AppReminder>>,
  'getArmies' : ActorMethod<[], Array<Army>>,
  'getArmiesByCharacter' : ActorMethod<[CharacterId], Array<Army>>,
  'getArmyAlignment' : ActorMethod<[string], [] | [ArmyAlignmentEntry]>,
  'getArmyDoctrines' : ActorMethod<[string], Array<ArmyDoctrine>>,
  'getArmyLoot' : ActorMethod<[string], Array<ArmyLootEntry>>,
  'getArmyMetadata' : ActorMethod<[string], [] | [ArmyMetadata]>,
  'getArmyMoraleHistory' : ActorMethod<[string], Array<ArmyMoraleHistoryEntry>>,
  'getArmyOfficerSkills' : ActorMethod<[bigint], Array<OfficerSkillEntry>>,
  'getArmyRelationships' : ActorMethod<[string], Array<ArmyRelationship>>,
  'getArmyRivalEntries' : ActorMethod<[string], Array<ArmyRivalEntry>>,
  'getArmySupplyRoutes' : ActorMethod<[bigint], Array<SupplyRoute>>,
  'getAscensionLog' : ActorMethod<[string], Array<AscensionLogEntry>>,
  'getAttunedItems' : ActorMethod<[CharacterId], Array<AttunedItem>>,
  'getBattleEngagements' : ActorMethod<[string], Array<BattleEngagement>>,
  'getBattleOutcomes' : ActorMethod<[string], Array<BattleOutcome>>,
  'getBestiaryCreatures' : ActorMethod<[], Array<BestiaryCreature>>,
  'getBetrayalLog' : ActorMethod<[string], Array<BetrayalLogEntry>>,
  'getBlackBudgetLog' : ActorMethod<[string], Array<BlackBudgetEntry>>,
  'getBloodOathEntries' : ActorMethod<[string], Array<BloodOathEntry>>,
  'getBloodlineEntries' : ActorMethod<[string], Array<BloodlineEntry>>,
  'getBountyObjectives' : ActorMethod<[string], Array<BountyObjective>>,
  'getCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignEnemies' : ActorMethod<[string], Array<CampaignEnemy>>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getCapturedEnemies' : ActorMethod<[string], Array<CapturedEnemy>>,
  'getCelestialBlessings' : ActorMethod<
    [string],
    Array<CelestialBlessingEntry>
  >,
  'getCharacter' : ActorMethod<[CharacterId], [] | [Character]>,
  'getCharacterAppearance' : ActorMethod<
    [CharacterId],
    [] | [CharacterAppearance]
  >,
  'getCharacterConditions' : ActorMethod<
    [CharacterId],
    Array<CharacterCondition>
  >,
  'getCharacterCustomStatsByCharacter' : ActorMethod<
    [CharacterId],
    Array<CharacterCustomStat>
  >,
  'getCharacterFeatsByCharacter' : ActorMethod<
    [CharacterId],
    Array<CharacterFeat>
  >,
  'getCharacterInjuries' : ActorMethod<[CharacterId], Array<CharacterInjury>>,
  'getCharacterLegacies' : ActorMethod<[string], Array<CharacterLegacy>>,
  'getCharacterMulticlass' : ActorMethod<[CharacterId], Array<MulticlassEntry>>,
  'getCharacterProficienciesByCharacter' : ActorMethod<
    [CharacterId],
    Array<CharacterProficiency>
  >,
  'getCharacterRelationships' : ActorMethod<
    [string],
    Array<CharacterRelationship>
  >,
  'getCharacterSkillsByCharacter' : ActorMethod<
    [CharacterId],
    Array<CharacterSkill>
  >,
  'getClearanceLevels' : ActorMethod<[string], Array<ClearanceLevelEntry>>,
  'getCommendations' : ActorMethod<[string], Array<Commendation>>,
  'getConcentrationState' : ActorMethod<
    [CharacterId],
    [] | [ConcentrationState]
  >,
  'getContainmentBreachLog' : ActorMethod<
    [string],
    Array<ContainmentBreachEntry>
  >,
  'getCorruptionLog' : ActorMethod<[string], Array<CorruptionLogEntry>>,
  'getCourtMartialEntries' : ActorMethod<[string], Array<CourtMartialEntry>>,
  'getCurrencyState' : ActorMethod<[CharacterId], [] | [CurrencyState]>,
  'getCursedItemEntries' : ActorMethod<[string], Array<CursedItemEntry>>,
  'getDarkRitualLog' : ActorMethod<[string], Array<DarkRitualEntry>>,
  'getDeathSaveState' : ActorMethod<[CharacterId], [] | [DeathSaveState]>,
  'getDefectionEntries' : ActorMethod<[], Array<DefectionEntry>>,
  'getDemonClassLog' : ActorMethod<[string], Array<DemonClassEntry>>,
  'getDeploymentNotes' : ActorMethod<[string], Array<DeploymentMapNote>>,
  'getDiplomacyLog' : ActorMethod<[string], Array<DiplomacyEntry>>,
  'getDivineMandates' : ActorMethod<[string], Array<DivineMandateEntry>>,
  'getDreamVisionEntries' : ActorMethod<[string], Array<DreamVisionEntry>>,
  'getEncounterLog' : ActorMethod<[], Array<EncounterEntry>>,
  'getEnemyRoster' : ActorMethod<[string], Array<EnemyProfile>>,
  'getEquipmentSlots' : ActorMethod<[CharacterId], Array<EquipmentSlot>>,
  'getEspionageEntries' : ActorMethod<[string], Array<EspionageEntry>>,
  'getEthicsReviewLog' : ActorMethod<[string], Array<EthicsReviewEntry>>,
  'getFactions' : ActorMethod<[], Array<Faction>>,
  'getFallenSoldiers' : ActorMethod<[string], Array<FallenSoldierEntry>>,
  'getGainLossEntries' : ActorMethod<[string], Array<GainLossEntry>>,
  'getHPState' : ActorMethod<[CharacterId], [] | [HPState]>,
  'getHolyRelics' : ActorMethod<[string], Array<HolyRelicEntry>>,
  'getHolyWarLog' : ActorMethod<[string], Array<HolyWarEntry>>,
  'getInfernalDebtLog' : ActorMethod<[string], Array<InfernalDebtEntry>>,
  'getInitiativeTrackers' : ActorMethod<[], Array<InitiativeTracker>>,
  'getInspirationState' : ActorMethod<[CharacterId], [] | [InspirationState]>,
  'getInterPresetWarEntries' : ActorMethod<[], Array<InterPresetWarEntry>>,
  'getItemsByCharacter' : ActorMethod<
    [CharacterId],
    Array<[InventoryItemId, InventoryItem]>
  >,
  'getLanguagesByCharacter' : ActorMethod<[CharacterId], Array<Language>>,
  'getLocationDungeonRooms' : ActorMethod<[string], Array<DungeonRoom>>,
  'getLocations' : ActorMethod<[], Array<Location>>,
  'getLootDistributionLog' : ActorMethod<[], Array<LootDistributionEntry>>,
  'getLoreEntries' : ActorMethod<[], Array<LoreEntry>>,
  'getLostKnowledgeEntries' : ActorMethod<[], Array<LostKnowledgeEntry>>,
  'getMIAEntries' : ActorMethod<[string], Array<MIAEntry>>,
  'getMythologicalFigures' : ActorMethod<[], Array<MythologicalFigure>>,
  'getNPCs' : ActorMethod<[], Array<NPC>>,
  'getOfficerDuels' : ActorMethod<[string], Array<OfficerDuel>>,
  'getPactContractLog' : ActorMethod<[string], Array<PactContractEntry>>,
  'getPartyInventory' : ActorMethod<[], Array<PartyInventoryItem>>,
  'getPartyNotes' : ActorMethod<[], Array<PartyNote>>,
  'getPartyXpEntries' : ActorMethod<[], Array<PartyXpEntry>>,
  'getPersonalLoot' : ActorMethod<[CharacterId], Array<PersonalLootEntry>>,
  'getPhysicalAttacksByCharacter' : ActorMethod<
    [CharacterId],
    Array<[CharacterPhysicalAttackId, CharacterPhysicalAttack]>
  >,
  'getPlaneRealmEntry' : ActorMethod<[], [] | [PlaneRealmEntry]>,
  'getPortalEntries' : ActorMethod<[], Array<PortalEntry>>,
  'getPrayerLog' : ActorMethod<[string], Array<PrayerLogEntry>>,
  'getPreparedSpells' : ActorMethod<[CharacterId], Array<string>>,
  'getPrisonerExchanges' : ActorMethod<[string], Array<PrisonerExchangeEntry>>,
  'getProphecyEntries' : ActorMethod<[], Array<ProphecyEntry>>,
  'getProtocolLog' : ActorMethod<[string], Array<ProtocolLogEntry>>,
  'getPsychEvalLog' : ActorMethod<[string], Array<PsychEvalEntry>>,
  'getQuestsByCharacter' : ActorMethod<[CharacterId], Array<Quest>>,
  'getRealmTerritoryLog' : ActorMethod<[string], Array<RealmTerritoryEntry>>,
  'getReclassificationLog' : ActorMethod<
    [string],
    Array<ReclassificationEntry>
  >,
  'getRecruitmentLog' : ActorMethod<[string], Array<RecruitmentEntry>>,
  'getRestState' : ActorMethod<[CharacterId], [] | [RestState]>,
  'getRivals' : ActorMethod<[CharacterId], Array<RivalEntry>>,
  'getSaveThrowState' : ActorMethod<[CharacterId], [] | [SaveThrowState]>,
  'getScpObjectLog' : ActorMethod<[string], Array<ScpObjectEntry>>,
  'getSecretMissionLogs' : ActorMethod<[string], Array<SecretMissionLog>>,
  'getSessionLog' : ActorMethod<[], Array<SessionEntry>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getSiegeEntries' : ActorMethod<[string], Array<SiegeEntry>>,
  'getSinCorruptionLog' : ActorMethod<[string], Array<SinCorruptionEntry>>,
  'getSiteAssignmentLog' : ActorMethod<[string], Array<SiteAssignmentEntry>>,
  'getSoldierBios' : ActorMethod<[string], Array<SoldierBio>>,
  'getSoulBountyLog' : ActorMethod<[string], Array<SoulBountyEntry>>,
  'getSpellSlotsByCharacter' : ActorMethod<
    [CharacterId],
    Array<SpellSlotState>
  >,
  'getSpellsByCharacter' : ActorMethod<[CharacterId], Array<[SpellId, Spell]>>,
  'getSrdSpells' : ActorMethod<[], Array<SrdSpell>>,
  'getSummoningLog' : ActorMethod<[string], Array<SummoningLogEntry>>,
  'getSupplyConsumptionLog' : ActorMethod<
    [string],
    Array<SupplyConsumptionEntry>
  >,
  'getTabNote' : ActorMethod<[CharacterId, string], [] | [TabNote]>,
  'getThemeSettings' : ActorMethod<[], [] | [ThemeSettings]>,
  'getTimelineEvents' : ActorMethod<[], Array<TimelineEvent>>,
  'getTrainingCertifications' : ActorMethod<
    [string],
    Array<TrainingCertification>
  >,
  'getTraitsByCharacter' : ActorMethod<[CharacterId], Array<[TraitId, Trait]>>,
  'getTrophyEntries' : ActorMethod<[string], Array<TrophyEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVeteranUnits' : ActorMethod<[string], Array<VeteranUnit>>,
  'getWarCrimeEntries' : ActorMethod<[string], Array<WarCrimeEntry>>,
  'getWeatherEntries' : ActorMethod<[], Array<WeatherEntry>>,
  'getWhistleblowerLog' : ActorMethod<[string], Array<WhistleblowerEntry>>,
  'getXpState' : ActorMethod<[CharacterId], [] | [XpState]>,
  'importAllData' : ActorMethod<[string], boolean>,
  'importCharacter' : ActorMethod<[ImportCharacterInput], CharacterId>,
  'initializeSrdSpells' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logSupplyConsumption' : ActorMethod<
    [string, SupplyConsumptionEntry],
    undefined
  >,
  'removeAttunedItem' : ActorMethod<[CharacterId, string], undefined>,
  'saveAppReminder' : ActorMethod<[AppReminder], boolean>,
  'saveArmyAlignment' : ActorMethod<[ArmyAlignmentEntry], boolean>,
  'saveArmyMetadata' : ActorMethod<[ArmyMetadata], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveInitiativeTracker' : ActorMethod<[InitiativeTracker], boolean>,
  'savePlaneRealmEntry' : ActorMethod<[PlaneRealmEntry], boolean>,
  'saveTabNote' : ActorMethod<[CharacterId, string, string], undefined>,
  'setPreparedSpells' : ActorMethod<[CharacterId, Array<string>], undefined>,
  'simulateBattle' : ActorMethod<[bigint, bigint], BattleSimResult>,
  'updateAllianceTreaty' : ActorMethod<[AllianceTreaty], boolean>,
  'updateAlly' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateAmnesticLogEntry' : ActorMethod<[AmnesticLogEntry], boolean>,
  'updateAncientHistoryEntry' : ActorMethod<[AncientHistoryEntry], boolean>,
  'updateAngelClassEntry' : ActorMethod<[AngelClassEntry], boolean>,
  'updateAnomalyExposureEntry' : ActorMethod<[AnomalyExposureEntry], boolean>,
  'updateArmy' : ActorMethod<[string, ArmyInput], undefined>,
  'updateArmyBanner' : ActorMethod<[string, string], undefined>,
  'updateArmyDoctrine' : ActorMethod<[ArmyDoctrine], boolean>,
  'updateArmyLootEntry' : ActorMethod<[string, ArmyLootEntry], boolean>,
  'updateArmyOfficerSkills' : ActorMethod<
    [bigint, Array<OfficerSkillEntry>],
    boolean
  >,
  'updateArmyRelationships' : ActorMethod<
    [string, Array<ArmyRelationship>],
    undefined
  >,
  'updateArmyRivalEntry' : ActorMethod<[ArmyRivalEntry], boolean>,
  'updateArmySupplyRoutes' : ActorMethod<[bigint, Array<SupplyRoute>], boolean>,
  'updateAscensionLogEntry' : ActorMethod<[AscensionLogEntry], boolean>,
  'updateBattleOutcome' : ActorMethod<[BattleOutcome], boolean>,
  'updateBestiaryCreature' : ActorMethod<[BestiaryCreature], boolean>,
  'updateBetrayalLogEntry' : ActorMethod<[BetrayalLogEntry], boolean>,
  'updateBlackBudgetEntry' : ActorMethod<[BlackBudgetEntry], boolean>,
  'updateBloodOathEntry' : ActorMethod<[BloodOathEntry], boolean>,
  'updateBloodlineEntry' : ActorMethod<[BloodlineEntry], boolean>,
  'updateBountyObjective' : ActorMethod<[string, BountyObjective], boolean>,
  'updateCalendarEvent' : ActorMethod<[CalendarEvent], boolean>,
  'updateCampaign' : ActorMethod<[Campaign], undefined>,
  'updateCampaignEnemy' : ActorMethod<[string, CampaignEnemy], boolean>,
  'updateCapturedEnemy' : ActorMethod<[CapturedEnemy], boolean>,
  'updateCelestialBlessing' : ActorMethod<[CelestialBlessingEntry], boolean>,
  'updateCharacter' : ActorMethod<[CharacterId, Character], undefined>,
  'updateCharacterAbility' : ActorMethod<
    [CharacterAbilityId, CharacterAbility],
    undefined
  >,
  'updateCharacterAppearance' : ActorMethod<
    [CharacterId, CharacterAppearance],
    boolean
  >,
  'updateCharacterConditions' : ActorMethod<
    [CharacterId, Array<CharacterCondition>],
    boolean
  >,
  'updateCharacterCustomStat' : ActorMethod<[bigint, string], undefined>,
  'updateCharacterFeat' : ActorMethod<[bigint, string, string], undefined>,
  'updateCharacterInjury' : ActorMethod<[string, CharacterInjury], boolean>,
  'updateCharacterLegacy' : ActorMethod<[CharacterLegacy], boolean>,
  'updateCharacterMulticlass' : ActorMethod<
    [CharacterId, Array<MulticlassEntry>],
    boolean
  >,
  'updateCharacterPhysicalAttack' : ActorMethod<
    [CharacterPhysicalAttackId, CharacterPhysicalAttack],
    undefined
  >,
  'updateCharacterPortrait' : ActorMethod<[CharacterId, string], undefined>,
  'updateCharacterRelationship' : ActorMethod<[CharacterRelationship], boolean>,
  'updateCharacterSkill' : ActorMethod<
    [bigint, string, boolean, boolean],
    undefined
  >,
  'updateClass' : ActorMethod<[ClassId, CustomClass], undefined>,
  'updateClearanceLevelEntry' : ActorMethod<[ClearanceLevelEntry], boolean>,
  'updateCommendation' : ActorMethod<[Commendation], boolean>,
  'updateConcentrationState' : ActorMethod<
    [CharacterId, ConcentrationState],
    undefined
  >,
  'updateContainmentBreachEntry' : ActorMethod<
    [ContainmentBreachEntry],
    boolean
  >,
  'updateCorruptionLogEntry' : ActorMethod<[CorruptionLogEntry], boolean>,
  'updateCourtMartialEntry' : ActorMethod<[CourtMartialEntry], boolean>,
  'updateCurrencyState' : ActorMethod<[CharacterId, CurrencyState], undefined>,
  'updateCursedItemEntry' : ActorMethod<[CursedItemEntry], boolean>,
  'updateCustomAbility' : ActorMethod<
    [CustomAbilityId, CustomAbility],
    undefined
  >,
  'updateCustomFeat' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateCustomItem' : ActorMethod<[CustomItemId, CustomItem], undefined>,
  'updateCustomPhysicalAttack' : ActorMethod<
    [CustomPhysicalAttackId, CustomPhysicalAttack],
    undefined
  >,
  'updateCustomSkill' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateCustomSpell' : ActorMethod<[CustomSpellId, CustomSpell], undefined>,
  'updateCustomSpellSchool' : ActorMethod<
    [CustomSpellSchoolId, CustomSpellSchool],
    undefined
  >,
  'updateCustomStat' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateDarkRitualEntry' : ActorMethod<[DarkRitualEntry], boolean>,
  'updateDeathSaveState' : ActorMethod<
    [CharacterId, DeathSaveState],
    undefined
  >,
  'updateDefectionEntry' : ActorMethod<[DefectionEntry], boolean>,
  'updateDemonClassEntry' : ActorMethod<[DemonClassEntry], boolean>,
  'updateDeploymentNote' : ActorMethod<[string, DeploymentMapNote], boolean>,
  'updateDiplomacyEntry' : ActorMethod<[string, DiplomacyEntry], boolean>,
  'updateDivineMandate' : ActorMethod<[DivineMandateEntry], boolean>,
  'updateDreamVisionEntry' : ActorMethod<[DreamVisionEntry], boolean>,
  'updateEncounterEntry' : ActorMethod<[EncounterEntry], undefined>,
  'updateEnemyProfile' : ActorMethod<[string, EnemyProfile], boolean>,
  'updateEquipmentSlots' : ActorMethod<
    [CharacterId, Array<EquipmentSlot>],
    undefined
  >,
  'updateEspionageEntry' : ActorMethod<[EspionageEntry], boolean>,
  'updateEthicsReviewEntry' : ActorMethod<[EthicsReviewEntry], boolean>,
  'updateFaction' : ActorMethod<[Faction], boolean>,
  'updateFallenSoldier' : ActorMethod<[FallenSoldierEntry], boolean>,
  'updateGainLossEntry' : ActorMethod<[string, GainLossEntry], boolean>,
  'updateHPState' : ActorMethod<[CharacterId, HPState], undefined>,
  'updateHolyRelic' : ActorMethod<[HolyRelicEntry], boolean>,
  'updateHolyWarEntry' : ActorMethod<[HolyWarEntry], boolean>,
  'updateInfernalDebtEntry' : ActorMethod<[InfernalDebtEntry], boolean>,
  'updateInspirationState' : ActorMethod<
    [CharacterId, InspirationState],
    undefined
  >,
  'updateInterPresetWarEntry' : ActorMethod<[InterPresetWarEntry], boolean>,
  'updateItem' : ActorMethod<[InventoryItemId, InventoryItem], undefined>,
  'updateLanguage' : ActorMethod<[bigint, string], undefined>,
  'updateLocation' : ActorMethod<[Location], undefined>,
  'updateLocationDungeonRooms' : ActorMethod<
    [string, Array<DungeonRoom>],
    boolean
  >,
  'updateLoreEntry' : ActorMethod<[LoreEntry], undefined>,
  'updateLostKnowledgeEntry' : ActorMethod<[LostKnowledgeEntry], boolean>,
  'updateMIAEntry' : ActorMethod<[MIAEntry], boolean>,
  'updateMythologicalFigure' : ActorMethod<[MythologicalFigure], boolean>,
  'updateNPC' : ActorMethod<[NPC], undefined>,
  'updatePactContractEntry' : ActorMethod<[PactContractEntry], boolean>,
  'updatePartyInventoryItem' : ActorMethod<[PartyInventoryItem], undefined>,
  'updatePartyNote' : ActorMethod<[PartyNote], undefined>,
  'updatePersonalLootEntry' : ActorMethod<[string, PersonalLootEntry], boolean>,
  'updatePortalEntry' : ActorMethod<[PortalEntry], boolean>,
  'updatePrayerLogEntry' : ActorMethod<[PrayerLogEntry], boolean>,
  'updatePrisonerExchange' : ActorMethod<
    [string, PrisonerExchangeEntry],
    boolean
  >,
  'updateProphecyEntry' : ActorMethod<[ProphecyEntry], boolean>,
  'updateProtocolLogEntry' : ActorMethod<[ProtocolLogEntry], boolean>,
  'updatePsychEvalEntry' : ActorMethod<[PsychEvalEntry], boolean>,
  'updateQuest' : ActorMethod<[CharacterId, Quest], undefined>,
  'updateRace' : ActorMethod<[RaceId, CustomRace], undefined>,
  'updateRaceLinkedContent' : ActorMethod<
    [RaceId, RaceLinkedContent],
    undefined
  >,
  'updateRealmTerritoryEntry' : ActorMethod<[RealmTerritoryEntry], boolean>,
  'updateReclassificationEntry' : ActorMethod<[ReclassificationEntry], boolean>,
  'updateRestState' : ActorMethod<[CharacterId, RestState], undefined>,
  'updateRivalEntry' : ActorMethod<[string, RivalEntry], boolean>,
  'updateSaveThrowState' : ActorMethod<
    [CharacterId, SaveThrowState],
    undefined
  >,
  'updateScpObjectEntry' : ActorMethod<[ScpObjectEntry], boolean>,
  'updateSecretMissionLog' : ActorMethod<[SecretMissionLog], boolean>,
  'updateSessionEntry' : ActorMethod<[SessionEntry], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateSiegeEntry' : ActorMethod<[SiegeEntry], boolean>,
  'updateSinCorruptionEntry' : ActorMethod<[SinCorruptionEntry], boolean>,
  'updateSiteAssignmentEntry' : ActorMethod<[SiteAssignmentEntry], boolean>,
  'updateSoldierBio' : ActorMethod<[SoldierBio], boolean>,
  'updateSoulBountyEntry' : ActorMethod<[SoulBountyEntry], boolean>,
  'updateSpell' : ActorMethod<[SpellId, Spell], undefined>,
  'updateSpellSlots' : ActorMethod<
    [CharacterId, Array<SpellSlotState>],
    undefined
  >,
  'updateSummoningLogEntry' : ActorMethod<[SummoningLogEntry], boolean>,
  'updateThemeSettings' : ActorMethod<[ThemeSettings], boolean>,
  'updateTimelineEvent' : ActorMethod<[TimelineEvent], undefined>,
  'updateTrainingCertification' : ActorMethod<[TrainingCertification], boolean>,
  'updateTrait' : ActorMethod<[TraitId, Trait], undefined>,
  'updateTrophyEntry' : ActorMethod<[TrophyEntry], boolean>,
  'updateVeteranUnit' : ActorMethod<[VeteranUnit], boolean>,
  'updateWarCrimeEntry' : ActorMethod<[WarCrimeEntry], boolean>,
  'updateWeatherEntry' : ActorMethod<[WeatherEntry], boolean>,
  'updateWhistleblowerEntry' : ActorMethod<[WhistleblowerEntry], boolean>,
  'updateXpState' : ActorMethod<[CharacterId, XpState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];